<template>
  <div class="mx-10 my-5 leading-8">
     <h1 class="text-2xl text-indigo-500 font-bold">SHIFT: Synthetic Feeder Model Generation Tool</h1>
    <p class="non-italic mb-5 text-base text-gray-800 font-bold"> Use cases for SHIFT data set </p>
    <p> Distribution feeder models generated using SHIFT could be used in following use cases. These use cases are not complete set of all possible use case but are popular ones. </p>
    <p class="text-indigo-600 border-b-2 font-bold border-gray-300 mt-5 mb-3"> Techno Economic Analysis  </p>
    <p> Techno economic analysis requires actual load consumption, output of generating sources, thermal loadings on the assets,
      losses in the system and more. Time series staedy state power flow analysis on distribution system model can be used
      to generate these data. The distribution system models generated by SHIFT can be used to perform steady state analysis thus helping
      performing techno economic study.
    </p>
    <p class="text-indigo-600 border-b-2 font-bold border-gray-300 mt-5 mb-3"> Hosting Capacity Analysis  </p>
    <p>Hosting capacity analysis allows us to determine the ability of distribution system to host wide variety of DER resources. For e.g. PV hosting capacity analysis can be used
      to determine total PV capacity a distribution feeder can integrate without requiring any upgrade and without impacting system reliability. Hosting capacity is not limited
      to just PV (also known as solar) but can be performed for electric vehicles, energy storage and more. Performing hosting capacity analysis requires developing futuristic scenarios and conducting
      powerflow analysis to determine system impact. Distribution system models generated by SHIFT could act as base case which you can then use to develop
      futuristic scenarios against it to perform hosting capacity analysis.
    </p>

    <p class="text-indigo-600 border-b-2 font-bold border-gray-300 mt-5 mb-3"> Upgrade Cost Analysis  </p>
    <p> Whenever a customer and/or DER resources is added to the distribution system, utilities may need to upgrade thier existing system. Upgrade could be upsizing 
      distribution transformer or reconductoring. These upgrades are costly and upgrade cost analysis helps utilities determine least cost 
      pathway for performing these upgrades. Detailed distribution model is key to performing upgrade cost analysis.
    </p>

    <p class="text-indigo-600 border-b-2 font-bold border-gray-300 mt-5 mb-3"> Interconnection Assessment  </p>
    <p>
        Nowadays utilities are facing large number of distributed energy resource integration applications. These Interconnection applications need to be 
        thoroughly assessed before being approved. Currently planning engineers analyze these applications manually and is taking close to a month to process single application. Whether you are
        analyzing manually or in automated fashion, having a detailed distribution system model is a must to effectively process these applications. 
    </p>

    <p class="text-indigo-600 border-b-2 font-bold border-gray-300 mt-5 mb-3"> Impact of SMART Inverters  </p>
    <p> Inverters are devices that convert DC power (e.g. power coming from battery, solar) into AC power (power that our home applicances use for e.g Motors, Lamps, ACs etc). SMART inverters are special type of inverters whose output power can be 
      controlled. Controlling power output from inverter can improve reliability and performance of existing distribution system. Understanding how these SMART inverters can be useful in deferring system
      upgrades can be extremely valuable. Distribution system models can help utilities understand impact of SMART inverter settings.
    </p>
  </div>
</template>

<script>
export default {
    name: "shiftUseCases"
}
</script>

<style>

</style>